# -*- coding: utf-8 -*-
"""load_sta_met.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pYD693vsyiWAWieg8AYDSXE2SCcpsFuO
"""

from google.colab import files
uploaded = files.upload()

import pandas as pd

# ==============================
# 1. 读取 sta.csv（分钟级管网数据）
# ==============================
sta = pd.read_csv("sta.csv")

# 时间列转为 datetime
sta["Datetime"] = pd.to_datetime(sta["Datetime"])

# 设置时间索引并排序
sta = sta.set_index("Datetime").sort_index()

# 选取建模需要的列
sta = sta[
    [
        "WaterLevel(m)",      # 液位（预测目标）
        "Flow(L/s)",          # 流量
        "Velocity(m/s)",      # 流速
        "WaterTemperature(_)" # 水温
    ]
]

# 确保时间频率为 1 分钟
sta = sta.resample("1min").mean()


# ==============================
# 2. 读取 met.csv（小时级气象数据）
# ==============================
met = pd.read_csv("met.csv")

met["Datetime"] = pd.to_datetime(met["Datetime"])
met = met.set_index("Datetime").sort_index()

met = met[
    [
        "Precipiation(mm)",     # 降雨
        "AirTemperature(_)",    # 气温
        "RelativeHumidity(%)",  # 湿度
        "VaporPressure(kPa)",   # 水汽压
        "WindSpeed(m/s)",       # 风速
        "WindDirection"         # 风向
    ]
]

# 确保是小时级
met = met.resample("1h").mean()


# ==============================
# 3. 小时 → 分钟 对齐（关键步骤）
# ==============================
# 使用前向填充：一个小时内气象条件保持不变
met_aligned = met.reindex(sta.index, method="ffill")


# ==============================
# 4. 合并数据
# ==============================
df = pd.concat([sta, met_aligned], axis=1)

# ==============================

# 删除仍存在缺失值的时间点
df = df.dropna()

print(df.head())
print(df.shape)

df.head(10)

df.tail(10)

df_train = df.loc["2022-10-01":"2022-11-11"]
df_forecast = df.loc["2022-11-11":"2022-12-01"]
df_reference = df.loc["2022-10-20":"2022-11-10"]
df_anomaly = df.loc["2023-01-01":"2023-02-01"]

df_train.head()

df_train.tail()

df_forecast.head()

df_forecast.tail()

df_reference.head()

df_reference.tail()

df_anomaly.head()

df_anomaly.tail()

df.to_csv("df.csv")
df_train.to_csv("df_train.csv")
df_forecast.to_csv("df_forecast.csv")
df_reference.to_csv("df_reference.csv")
df_anomaly.to_csv("df_anomaly.csv")

files.download("df.csv")
files.download("df_train.csv")
files.download("df_forecast.csv")
files.download("df_reference.csv")
files.download("df_anomaly.csv")

import matplotlib.pyplot as plt

plt.figure(figsize=(12,4))
plt.plot(df_train.index, df_train["WaterLevel(m)"], linewidth=0.8)
plt.xlabel("Time")
plt.ylabel("Water Level (m)")
plt.title("Water Level Time Series (Training Period)")
plt.tight_layout()
plt.show()

plt.figure(figsize=(6,4))
plt.hist(
    df_train["WaterLevel(m)"],
    bins=50,
    alpha=0.6,
    label="Train",
    density=True
)
plt.hist(
    df_forecast["WaterLevel(m)"],
    bins=50,
    alpha=0.6,
    label="Forecast",
    density=True
)
plt.xlabel("Water Level (m)")
plt.ylabel("Density")
plt.title("Distribution Comparison: Train vs Forecast")
plt.legend()
plt.tight_layout()
plt.show()

hourly_reference = (
    df_reference["WaterLevel(m)"]
    .groupby(df_reference.index.hour)
    .mean()
)

plt.figure(figsize=(6,4))
plt.plot(hourly_reference.index, hourly_reference.values, marker="o")
plt.xlabel("Hour of Day")
plt.ylabel("Average Water Level (m)")
plt.title("Diurnal Pattern (Reference Period)")
plt.xticks(range(0,24))
plt.grid(alpha=0.3)
plt.tight_layout()
plt.show()

hourly_anomaly = (
    df_anomaly["WaterLevel(m)"]
    .groupby(df_anomaly.index.hour)
    .mean()
)

plt.figure(figsize=(6,4))
plt.plot(hourly_reference.index, hourly_reference.values, label="Reference")
plt.plot(hourly_anomaly.index, hourly_anomaly.values, label="Anomaly Period")
plt.xlabel("Hour of Day")
plt.ylabel("Average Water Level (m)")
plt.title("Diurnal Pattern Comparison")
plt.legend()
plt.grid(alpha=0.3)
plt.tight_layout()
plt.show()

plt.figure(figsize=(12,4))
plt.plot(df_anomaly.index, df_anomaly["WaterLevel(m)"], linewidth=0.8)
plt.xlabel("Time")
plt.ylabel("Water Level (m)")
plt.title("Water Level Time Series (Anomaly Detection Period)")
plt.tight_layout()
plt.show()

