# -*- coding: utf-8 -*-
"""load_inflow_loading_obs.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16xQq44cAKYHQFkGsFx6s2BqzyEBBIIT1
"""

from google.colab import files
uploaded = files.upload()

import pandas as pd


def load_inflow_loading_obs(
    file_path="inflow_loading_obs.xlsx",
    sheet_name=0
):
    """
    读取并整理 inflow_loading_obs.xlsx 数据
    用于问题（3）obs 预测 与 问题（4）成因分析

    参数
    ----------
    file_path : str
        Excel 文件路径（默认使用 Colab Upload 的 inflow_loading_obs.xlsx）
    sheet_name : int or str
        Excel 工作表名称或索引（默认第一个 sheet）

    返回
    ----------
    X : pandas.DataFrame
        输入特征（inflow + loading）
    Y : pandas.DataFrame
        输出目标（obs）
    df : pandas.DataFrame
        原始合并后的完整数据（便于后续分析）
    """

    # ============================
    # 1. 读取 Excel 文件
    # ============================
    df = pd.read_excel(file_path, sheet_name=sheet_name)

    # ============================
    # 2. 识别列名（按前缀分组）
    # ============================

    # inflow 特征
    inflow_cols = [c for c in df.columns if c.lower().startswith("inflow")]

    # loading 特征
    loading_cols = [c for c in df.columns if c.lower().startswith("loading")]

    # obs 输出
    obs_cols = [c for c in df.columns if c.lower().startswith("obs")]

    # ============================
    # 3. 构造输入 X 与输出 Y
    # ============================

    X = df[inflow_cols + loading_cols]
    Y = df[obs_cols]

    # ============================
    # 4. 基础数据清理
    # ============================

    # 删除存在缺失值的样本（保守做法）
    valid_index = X.notna().all(axis=1) & Y.notna().all(axis=1)
    X = X.loc[valid_index]
    Y = Y.loc[valid_index]
    df = df.loc[valid_index]

    # ============================
    # 5. 返回数据
    # ============================
    return X, Y, df

X, Y, df_obs = load_inflow_loading_obs("inflow_loading_obs.xlsx")

print("输入特征 X 维度:", X.shape)
print("输出目标 Y 维度:", Y.shape)

print("\nX 前几行：")
display(X.head())

print("\nY 前几行：")
display(Y.head())

# 输入特征描述统计
X.describe().T[["mean", "std", "min", "max"]]

# 输出 obs 描述统计
Y.describe().T[["mean", "std", "min", "max"]]

import matplotlib.pyplot as plt

Y.hist(
    figsize=(12,8),
    bins=50,
    layout=(4, 3)
)
plt.suptitle("Distribution of obs Variables", y=1.02)
plt.tight_layout()
plt.show()

corr = pd.concat([X, Y], axis=1).corr()
corr_xy = corr.loc[X.columns, Y.columns]

plt.figure(figsize=(6,4))
plt.boxplot(
    [X.filter(like="inflow").values.flatten(),
     X.filter(like="loading").values.flatten()],
    labels=["Inflow", "Loading"],
    showfliers=False
)
plt.ylabel("Value")
plt.title("Scale Comparison: Inflow vs Loading")
plt.tight_layout()
plt.show()

import matplotlib.pyplot as plt
import numpy as np
plt.figure(figsize=(10, 6))

im = plt.imshow(
    corr_xy.values,
    aspect="auto",
    cmap="coolwarm",
    vmin=-1,
    vmax=1
)

# 坐标轴
plt.xticks(
    ticks=np.arange(len(corr_xy.columns)),
    labels=corr_xy.columns,
    rotation=45,
    ha="right"
)
plt.yticks(
    ticks=np.arange(len(corr_xy.index)),
    labels=corr_xy.index
)

plt.colorbar(im, label="Correlation Coefficient")
plt.title("Correlation between Inflow/Loading and obs Variables")
plt.tight_layout()
plt.show()

